### ISSUE TITLE
R2D2 can't connect to the Millenium Falcon

### ISSUE THREAD

**Issue by lovisall** [ToddBooth/TestingItSystems#12]
** R2D2 keeps getting electrocuted when trying to connect to the Millenium Falcon, please help him! **  

![r2d2-connecting](https://user-images.githubusercontent.com/65532698/82190060-b9807d00-98f0-11ea-9a81-d62ba44e6052.gif)

**Comment by ToddBooth** [comment]
Try the open button.  Nice gif
