### ISSUE TITLE
Strange pirates appearing

### ISSUE THREAD

**Issue by fredrik365** [ToddBooth/TestingItSystems#18]
At first it went fine to read the instructions but after a while this weird pirate ship appeared. I do not know how I triggered it? See picture below. 

![github](https://user-images.githubusercontent.com/63882786/82249806-be721a80-994a-11ea-9889-f5a3df2e91df.png)

My study budy Max resolved the issue because when he opened the file the pirates were gone. I guess he scared them away...

**Comment by mackelito123** [comment]
I fixed this issue

**Comment by fredrik365** [comment]
Thanks! I hope thay are gone for good!
