### ISSUE TITLE
Default System.out stream does not support UTF-8 encoding

### ISSUE THREAD

**Issue by AntonH91** [ToddBooth/TestingItSystems#20]
It looks quite terrible with our headline dump from SVT.

![Capture](https://user-images.githubusercontent.com/63237093/82337780-6d1a6780-99ec-11ea-8498-f62de2926df1.PNG)

**Comment by AntonH91** [comment]
I know using PrintWriter with the standard utf-8 encoder fixes the issue, but that's a hassle. :(

**Comment by ToddBooth** [comment]
Try English to reduce the number of errors.
