### ISSUE TITLE
Can't connect my AirPods to the Apple TV

### ISSUE THREAD

**Issue by philipberngarn** [ToddBooth/TestingItSystems#23]
**I want to connect my AirPods to the Apple TV**

![Apple](https://user-images.githubusercontent.com/64478667/82372577-7fac9500-9a1c-11ea-8eff-a5f14fb5368a.jpg)
![Apple1](https://user-images.githubusercontent.com/64478667/82372594-876c3980-9a1c-11ea-838f-a4a15a3b22d7.jpg)

**Comment by ToddBooth** [comment]
Nice picture and good luck.
