### ISSUE TITLE
Error when “git push” to github

### ISSUE THREAD

**Issue by rebeccahansson** [ToddBooth/TestingItSystems#24]
THIS IS NOT AN REAL ISSUE

I have a public repository at github.com with 2 branches : master and test.

I created a new directory locally and did:

[ ] git clone git@github.com:{username}/{projectname}.git
Then I created a new branch named my_test with

[ ] git branch my_test
and switched to it.

[ ] git checkout my_test
Then I merged it from my test branch of my public repository with

[ ] git merge origin/test
and it resulted in a fast forward.

I made some changes and committed them. Then I tried to push the local my_test branch to the public test branch at github with

[ ] git push git@github.com:{username}/{projectname}.git test 
but I got this error:

error: src refspec test does not match any.
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'git@github.com:{username}/{projectname}.git
<img width="765" alt="Screen Shot 2020-05-20 at 11 59 03" src="https://user-images.githubusercontent.com/65606281/82389862-52e69500-9a91-11ea-854e-77653f92d9be.png">

**Comment by ToddBooth** [comment]
Please try again.
