### ISSUE TITLE
Selenium hacked my computer

### ISSUE THREAD

**Issue by SimonNilssonGit** [ToddBooth/TestingItSystems#25]
*I installed Selenium and it stole all my passwords, emptied all my bank accounts and deleted all my school work. I risk becoming homeless...*

**Do you have a solution for this?**

![image](https://user-images.githubusercontent.com/64954248/82433654-0cde0100-9a92-11ea-8241-4187c0a879e2.png)

**Comment by ToddBooth** [comment]
No, don't become homeless and nice picture.
