### ISSUE TITLE
Selenium kidnapped my kids and stole my bank account :(

### ISSUE THREAD

**Issue by damplastbil** [ToddBooth/TestingItSystems#26]
I'm left with nothing. I'm sitting alone in my room and crying right now. Selenium was the worst decision I could have made.
![hackr](https://user-images.githubusercontent.com/28788294/82448031-71588a80-9aa9-11ea-8161-864a1c5e669a.jpg)

**Comment by ToddBooth** [comment]
Sorry to hear about that, nice picture.
