### ISSUE TITLE
Selenium Netbeans Program not working

### ISSUE THREAD

**Issue by johsei-9** [ToddBooth/TestingItSystems#28]
My Selenium Test wont complete all the steps, stops after opening youtube in firefox.
![bild](https://user-images.githubusercontent.com/65666304/82455183-f4321300-9ab2-11ea-9ebe-0b3bf94c4f5b.png)

**Comment by johsei-9** [comment]
I have fixed the issue with my program and it now works as intended:
![bild](https://user-images.githubusercontent.com/65666304/82456887-162c9500-9ab5-11ea-865b-2d91ddeda896.png)
![bild](https://user-images.githubusercontent.com/65666304/82456967-2cd2ec00-9ab5-11ea-86c3-1e4f7d263fee.png)
![bild](https://user-images.githubusercontent.com/65666304/82457107-555ae600-9ab5-11ea-8e64-df3f7af98ff8.png)

**Comment by ToddBooth** [comment]
It's OK, by default they assign to me.  Only if you are added to the repository by me, can you assign it to someone else.
