### ISSUE TITLE
Alternative link for setting up selenium in netbeans

### ISSUE THREAD

**Issue by mattekatten** [ToddBooth/TestingItSystems#32]
We had problems with following the youtube tutorial that was linked with the lab so we used this alternative link which helped us setup netbeans.

We downloaded and used a chrome driver instead of the firefox one in the example below.
![asdasdasdsadsad](https://user-images.githubusercontent.com/64011895/82546131-f26e5b00-9b57-11ea-9bc2-9d6e91459c9f.PNG)

https://softwaretestingbooks.com/selenium-webdriver-script-in-netbeans-using-firefox

![asdasdsadasd](https://user-images.githubusercontent.com/64011895/82546173-00bc7700-9b58-11ea-82f7-65ad52ea1ec9.PNG)

**Comment by ToddBooth** [comment]
Great work solving the problem and getting it working for NetBeans.
