### ISSUE TITLE
Wrong text in lab description

### ISSUE THREAD

**Issue by Linus-LM** [ToddBooth/TestingItSystems#37]
It appears that video number 3 and 4 in the "See the following videos" numbered list in the lab description are not videos but instead web pages.  Number 4 is correctly referenced as a web page, However, number 3 is not and should be addressed as a web page and not as a video.  The list could be for example "See the following videos and web pages" instead of only videos as this implies that there are only videos in the list.  See the screenshot below for where the issue occurs in the text.  Can you fix this @ToddBooth? 
![Lab 10 issue](https://user-images.githubusercontent.com/65597086/82732156-c267b900-9d0b-11ea-90dd-f054311f0dc0.PNG)

**Comment by Linus-LM** [comment]
Forgot to add the screenshot at first, which is why it says "edited" at the top

**Comment by Linus-LM** [comment]
Forgot to add the tag at first, which is why it says edited at the top.

**Comment by ToddBooth** [comment]
Thanks so much for the great issue!!!  Fixed and closed.
