### ISSUE TITLE
Wrong date for when AWS-credits cease its value

### ISSUE THREAD

**Issue by albdah9** [ToddBooth/TestingItSystems#38]
(fake issue)

On our AWS page it is stated that the AWS-credits of $50 cease its value already the 3rd of january, 2021. It is instead stated in the lab description that the credits are good until april, same year.  Would be good if the date is changed to the correct date and month so all participants of the course can use their instances fully in time. Can you fix this @ToddBooth ? See screenshot for info.
![image](https://user-images.githubusercontent.com/65311506/82732435-73bb1e80-9d0d-11ea-9f35-727df08782bb.png)

**Comment by ToddBooth** [comment]
My page says it will expire in April, but perhaps that is just for the teacher.

Thanks so much !!!  for the information, I've updated the page and closed the issue.

Teacher Todd
