### ISSUE TITLE
grupp 19 trying issues

### ISSUE THREAD

**Issue by lendal-9** [ToddBooth/TestingItSystems#39]
**grupp 19**
Manage to get this far atleast. Now try to get further in to this. 
![P_20200213_174412_vHDR_On](https://user-images.githubusercontent.com/65855192/82755068-9f9fd800-9dd1-11ea-8811-5428d0b2645c.jpg)

**Comment by Tati1711** [comment]
Very cute dogs )))

**Comment by lendal-9** [comment]
It appears that we managed to open an issue now lets ´close it
