### ISSUE TITLE
Please add elephants to the course

### ISSUE THREAD

**Issue by jnilssonn** [ToddBooth/TestingItSystems#45]
This is a picture to the animal elephant. Please take in mind the picture contains two of these animals.
https://images.app.goo.gl/PEZACj2trDFtPUt79
@ToddBooth do you have any experience working with these animals before? If not, below is a checklist to work through to make them happy enough to cooperate.

- [ ] Feed them bananas
- [ ] Don't make them climb trees, they will make you help them though.
- [ ] Give them a bucket of water every hour
- [ ] Turn on "America got Talent" every wensday afternoon, otherwise you'll see the defenition of a riot.

**Comment by ToddBooth** [comment]
Good one!
