### ISSUE TITLE
Dress color.

### ISSUE THREAD

**Issue by oskthy-7** [ToddBooth/TestingItSystems#46]
**This dress is not white and gold as stated**

*It's actually black and blue*

![](https://upload.wikimedia.org/wikipedia/en/a/a8/The_Dress_%28viral_phenomenon%29.png)

**Comment by oskthy-7** [comment]
> This dress is clearly white and gold

No. Just no.

**Comment by ToddBooth** [comment]
Maybe it's closer to blue.
