### ISSUE TITLE
Please change designation from video to webpage

### ISSUE THREAD

**Issue by mauritshjerpe** [ToddBooth/TestingItSystems#48]
The link on row 34 references a text web page rather than a video. See point 3 in the list in enclosed pic. Please change from video to webpage

![Skärmavbild 2020-05-30 kl  12 39 05](https://user-images.githubusercontent.com/64898638/83326353-a916bd80-a273-11ea-8b22-b7ad3c16f315.png)

**Comment by ToddBooth** [comment]
Thanks, updated and closed.
