### ISSUE TITLE
There is a typo in the assignment

### ISSUE THREAD

**Issue by simsjo-student** [ToddBooth/TestingItSystems#58]
The assignment point to a link to help us set up **NetBeans** and Firefox, but I think it should be **Selenium** and Firefox? 

![Skärmbild 2021-01-20 124707](https://user-images.githubusercontent.com/77697586/105171625-bfcd9580-5b1e-11eb-8a39-8e10d5f445bd.png)

**Comment by ToddBooth** [comment]
thanks
