### ISSUE TITLE
Change language to Danish - Hands-on Lab 10

### ISSUE THREAD

**Issue by donjuanuno** [ToddBooth/TestingItSystems#8]
I only understand Danish and not Swedish nor English so I would prefer the text at the "Hands-on Lab 10" to be changed to Danish.

![image](https://user-images.githubusercontent.com/65440903/82113777-e863eb00-9758-11ea-88f1-0298e4bd8243.png)

**Comment by ToddBooth** [comment]
Hænder på lab 10
